"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CDN_URL = exports.BASE_URL = exports.BASE_HOST = exports.DiscordEpoch = exports.EmbedColors = void 0;
var EmbedColors;
(function (EmbedColors) {
    EmbedColors[EmbedColors["Default"] = 0] = "Default";
    EmbedColors[EmbedColors["White"] = 16777215] = "White";
    EmbedColors[EmbedColors["Aqua"] = 1752220] = "Aqua";
    EmbedColors[EmbedColors["Green"] = 5763719] = "Green";
    EmbedColors[EmbedColors["Blue"] = 3447003] = "Blue";
    EmbedColors[EmbedColors["Yellow"] = 16705372] = "Yellow";
    EmbedColors[EmbedColors["Purple"] = 10181046] = "Purple";
    EmbedColors[EmbedColors["LuminousVividPink"] = 15277667] = "LuminousVividPink";
    EmbedColors[EmbedColors["Fuchsia"] = 15418782] = "Fuchsia";
    EmbedColors[EmbedColors["Gold"] = 15844367] = "Gold";
    EmbedColors[EmbedColors["Orange"] = 15105570] = "Orange";
    EmbedColors[EmbedColors["Red"] = 15548997] = "Red";
    EmbedColors[EmbedColors["Grey"] = 9807270] = "Grey";
    EmbedColors[EmbedColors["Navy"] = 3426654] = "Navy";
    EmbedColors[EmbedColors["DarkAqua"] = 1146986] = "DarkAqua";
    EmbedColors[EmbedColors["DarkGreen"] = 2067276] = "DarkGreen";
    EmbedColors[EmbedColors["DarkBlue"] = 2123412] = "DarkBlue";
    EmbedColors[EmbedColors["DarkPurple"] = 7419530] = "DarkPurple";
    EmbedColors[EmbedColors["DarkVividPink"] = 11342935] = "DarkVividPink";
    EmbedColors[EmbedColors["DarkGold"] = 12745742] = "DarkGold";
    EmbedColors[EmbedColors["DarkOrange"] = 11027200] = "DarkOrange";
    EmbedColors[EmbedColors["DarkRed"] = 10038562] = "DarkRed";
    EmbedColors[EmbedColors["DarkGrey"] = 9936031] = "DarkGrey";
    EmbedColors[EmbedColors["DarkerGrey"] = 8359053] = "DarkerGrey";
    EmbedColors[EmbedColors["LightGrey"] = 12370112] = "LightGrey";
    EmbedColors[EmbedColors["DarkNavy"] = 2899536] = "DarkNavy";
    EmbedColors[EmbedColors["Blurple"] = 5793266] = "Blurple";
    EmbedColors[EmbedColors["Greyple"] = 10070709] = "Greyple";
    EmbedColors[EmbedColors["DarkButNotBlack"] = 2895667] = "DarkButNotBlack";
    EmbedColors[EmbedColors["NotQuiteBlack"] = 2303786] = "NotQuiteBlack";
    EmbedColors[EmbedColors["DiscordDark"] = 3224376] = "DiscordDark";
    EmbedColors[EmbedColors["DiscordLight"] = 16382457] = "DiscordLight";
})(EmbedColors || (exports.EmbedColors = EmbedColors = {}));
exports.DiscordEpoch = 1420070400000n;
exports.BASE_HOST = 'https://discord.com';
exports.BASE_URL = `${exports.BASE_HOST}/api`;
exports.CDN_URL = 'https://cdn.discordapp.com';
